 p_belts
,  p_location
,  p_race
,  p_arresttype
,  p_charge
,  p_subagency
,  p_dateofstop
,  p_color
,  p_vehicletype
,  p_accident
,  p_state
,  p_violationtype
,  p_latitude
,  p_driverstate
,  p_model
,  p_personalinjury
,  p_article
,  p_description
,  p_hazmat
,  p_fatal
,  p_year
,  p_propertydamage
,  p_agency
,  p_gender
,  p_drivercity
,  p_longitude
,  p_alcohol
,  p_timeofstop
,  p_commercialvehicle
,  p_make
,  p_workzone
,  p_dlstate
,  p_contributedtoaccident
,  p_commerciallicense